# -*- coding: utf-8 -*-
"""pandas(team-2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPjPDLb1_H_LSRE9ERM3RdV3DaibusWz
"""

import pandas as pd
a=["sundar",'ramya','siri','sruthi','anu','lahari']
r = pd.Series(a,index=[67,43,44,89,23,18])
print(r)

df = pd.read_csv("/content/diabetcsv.csv")
print(df)

df = pd.read_csv("/content/grades_withnulls.csv")
print(df)

df = pd.read_csv("/content/grades_withnulls.csv",sep=" ")
print(df)

df = pd.read_excel("/content/grades_withnulls.xlsx")
print(df)

df = pd.read_excel("/content/grades_withnulls.xlsx",sheet_name=0)
print(df)

import pandas as pd
df=pd.read_csv("/content/diabetcsv.csv")
print(df.describe().T)

#making null value
df = pd.read_excel("/content/grades_withnulls.xlsx",sheet_name=0)
df2 = df.copy()
df2.loc[2:5,'SEM1']=None
df2.head(7)
df2.isnull().head(7)
print(df2.isnull().sum())
#extracting colum
print(df['SEM1'])
print(df[['SEM1','Names']])

#printing one row
print(df[df.index==1])

#printing multipule rows
print(df[df.index.isin(range(2,5))])

#printing one row as series
print(df2.loc[1])

df2.loc[6:11]

df2.loc[6:11,'Jess']==None
print(df2)

df2.loc[10:15,['Names','Grade']]

df2.loc[:7,["Names"]] #[rows,column]

df2.loc[df['Names']=='Mary']

df[df.Grade == 'A']
df[df.SEM2 == 10]

df.loc[df['SEM1'] >9.8,['Names']]

df3 = df2.copy()
df3= df3.dropna()
print(df3)

df3.dropna(inplace=True,axis=1)#inplace says not to re
df3

df3.dropna(inplace=True,how='all')
df3

mv = df3['SEM1'].mean()
dfn = df3.fillna(mv)
print(dfn)

