# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IU4Rb9yWrFjdH7Gj2dYhHYDD6AjFkCe_
"""

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
print(tips)
sns.scatterplot(x="sepal_len"  ,y="" ,data=tips)
plt.title("scatter ploat of total bill vs Tip")
plt.xlabel("Total bill ($)")
plt.ylabel("tip($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset("iris")
print(iris)
sns.scatterplot(x="sepal_length",y="sepal_width",data=iris,label="inside")
plt.title("scatter plot of Total Bill vs Tip")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tips ($)")
plt.legend(loc="best")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset("iris")
print(iris)
sns.barplot(x="sepal_length",y="sepal_width",data=iris,label="inside")
plt.title("scatter plot of Total Bill vs Tip")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tips ($)")
plt.legend(loc="best")
plt.show()



import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
sns.boxplot(x="day",y="total_bill",data=tips)
plt.title("scatter plot of Total Bill vs Tip")
plt.xlabel("day")
plt.ylabel("bill")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
a =pd.read_csv("/content/grades_withnulls.csv")
b=sns.lineplot(x='SEM1',y='SEM2',data=a)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
Iris = sns.load_dataset("iris")
correlation_matrix = iris.corr()
sns.heatmap(correlation_matrix, annot=True,cmap="coolwarm")
plt.title("correlation heatmap of Iris Dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset("iris")
print(iris)
sns.barplot(x="sepal_length",y="sepal_width",data=iris,label="inside")
plt.title("scatter plot of Total Bill vs Tip")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tips ($)")
plt.legend(loc="best")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
sns.countplot(x="day",data=tips)
plt.title("scatter plot of Total Bill vs Tip")
plt.xlabel("day")
plt.ylabel("bill")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
sns.lmplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of Total Bill vs Tip")
plt.xlabel("day")
plt.ylabel("bill")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
titanic=sns.load_dataset("titanic")
print(titanic)
g=sns.FacetGrid(titanic,col="class")
g.map(sns.histplot,"age")
plt.subplots_adjust(top=0.8)
g.fig.suptitle("Age Distribution by passenger class")
plt.show()